name: Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  bump_verison:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@saleshandy'

      - name: Install deps
        run: npm ci

      - name: Check Eslint
        run: npm run lint

      - name: Check Prettier
        run: npm run prettier:check

      - name: Run Test
        run: npm run test

      - name: Create Build
        run: npm run build

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
