name: Publish

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@saleshandy'

      - name: Install deps
        run: npm ci

      - name: Run Test
        run: npm run test

      - name: Create Build
        run: npm run build

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
