name: Release

on:
  workflow_run:
    workflows: [Bump Version]
    types:
      - completed

jobs:
  release:
    name: 'Release'

    runs-on: 'ubuntu-latest'

    permissions:
      contents: write

    steps:
      - name: 'Create release'
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
