name: Release

on:
  workflow_run:
    workflows: [Bump Version]
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
