name: Build and Deploy Storybook

on:
  push:
    paths:
      - 'src/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build-storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: storybook-static
          FOLDER: storybook-static
